# Generated by Django 5.2.8 on 2025-12-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_remembertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RememberToken',
        ),
    ]
